language: node_js

node_js:
  - "11.10.0"

cache:
  directories:
    - node_modules

before_install:
  - "npm --version"

install:
  - "npm install"

cache: npm

script:
  # Starting the server for testing
  - http-server -p 7000 > http.log 2>&1 &
  - npm run unit_test
  - npm run e2e_test
